version: '3.8'

services:
  # Backend API with SQLite
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: atlasiq-backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite+aiosqlite:///./data/atlasiq.db
      - JWT_SECRET_KEY=${JWT_SECRET_KEY:-your-super-secret-jwt-key-change-in-production}
      - JWT_ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - REFRESH_TOKEN_EXPIRE_DAYS=7
      - DEBUG=false
      - APP_ENV=production
    volumes:
      - backend-data:/app/data
    networks:
      - atlasiq-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Frontend (production build with nginx)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: atlasiq-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - atlasiq-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  backend-data:
    driver: local

networks:
  atlasiq-network:
    driver: bridge
