# Railway Backend Configuration

[build]
builder = "NIXPACKS"

[deploy]
startCommand = "python entrypoint.py"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[healthcheck]
path = "/health"
timeout = 300
interval = 30
