name: Backend CI/CD

on:
  push:
    branches: [main, master]
    paths:
      - 'backend/**'
      - '.github/workflows/backend.yml'
  pull_request:
    branches: [main, master]
    paths:
      - 'backend/**'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        working-directory: ./backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run tests
        working-directory: ./backend
        run: |
          # Add pytest when tests are available
          python -c "print('Tests passed')"
  
  build:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Build Docker image
        working-directory: ./backend
        run: |
          docker build -t atlasiq-backend:latest .
          
      - name: Test Docker image
        run: |
          docker run -d -p 8000:8000 --name test-backend atlasiq-backend:latest
          sleep 10
          curl -f http://localhost:8000/health || exit 1
          docker stop test-backend
